services:
  postgres:
    image: postgres:16
    container_name: ml-postgres
    environment:
      POSTGRES_DB: stockout_ml
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ml_user -d stockout_ml"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/artifacts
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://ml_user:ml_password@postgres:5432/stockout_ml
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../training:/opt/airflow/training
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Ekaterina --lastname Kuchina --role Admin --email kuchina.helper@gmail.com || true"

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://ml_user:ml_password@postgres:5432/stockout_ml
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../training:/opt/airflow/training
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://ml_user:ml_password@postgres:5432/stockout_ml
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../training:/opt/airflow/training
    command: scheduler

  fastapi-blue:
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: fastapi-blue
    environment:
      MODEL_VERSION: blue
      MODEL_PATH: /app/models/current/model.joblib
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    ports:
      - "8001:8000"
    volumes:
      - ../service:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  fastapi-green:
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: fastapi-green
    environment:
      MODEL_VERSION: green
      MODEL_PATH: /app/models/current/model.joblib
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    ports:
      - "8002:8000"
    volumes:
      - ../service:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27-alpine
    container_name: ml-nginx
    depends_on:
      fastapi-blue:
        condition: service_healthy
      fastapi-green:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.active.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: ml-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - fastapi-blue
      - fastapi-green

  grafana:
    image: grafana/grafana:latest
    container_name: ml-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  mlflow_data: