server {
    listen 80;
    server_name _;

    location /health {
        proxy_pass http://fastapi-blue:8000/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /predict {
        proxy_pass http://fastapi-blue:8000/predict;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /model-info {
        proxy_pass http://fastapi-blue:8000/model-info;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /metrics {
        proxy_pass http://fastapi-blue:8000/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 200 'nginx routes traffic to BLUE service\n';
        add_header Content-Type text/plain;
    }
}